//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adObjectCache
    {
        public string distinguishedName { get; set; }
        public string cn { get; set; }
        public string objectCategory { get; set; }
        public string objectClass { get; set; }
        public string name { get; set; }
        public string objectSID { get; set; }
        public string sn { get; set; }
        public string givenName { get; set; }
        public string sAMAccountName { get; set; }
        public string description { get; set; }
        public string info { get; set; }
        public string mail { get; set; }
        public string managedBy { get; set; }
        public string location { get; set; }
        public string department { get; set; }
        public string departmentNumber { get; set; }
        public string uceduUCID { get; set; }
        public Nullable<long> userAccountControl { get; set; }
        public string operatingSystem { get; set; }
        public Nullable<System.DateTime> whenCreated { get; set; }
        public Nullable<System.DateTime> whenChanged { get; set; }
        public Nullable<System.DateTime> TS { get; set; }
        public Nullable<bool> isEnabled { get; set; }
    }
}
