//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComputerInfo
    {
        public string hostname { get; set; }
        public string properties { get; set; }
        public string info { get; set; }
        public string SN { get; set; }
        public Nullable<System.DateTime> TS { get; set; }
    }
}
