//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventLog
    {
        public long id { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string Account { get; set; }
        public string Info { get; set; }
        public Nullable<System.DateTime> TS { get; set; }
        public string AffectedObjects { get; set; }
    }
}
