//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SI_CheckIn
    {
        public long id { get; set; }
        public string Hostname { get; set; }
        public string Username { get; set; }
        public string IP { get; set; }
        public string OS { get; set; }
        public string ServicePack { get; set; }
        public string Meta { get; set; }
        public Nullable<System.DateTime> TS { get; set; }
    }
}
